apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mvc-ingress
  namespace: multiapp-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: adminmvc-service
                port:
                  number: 80
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: usermvc-service
                port:
                  number: 80
