apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mvc-ingress
  namespace: multiapp-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: adminmvc-service
                port:
                  number: 80
            # ✅ ADMIN middleware
            middlewares:
              - name: strip-admin
                namespace: multiapp-prod

          - path: /user
            pathType: Prefix
            backend:
              service:
                name: usermvc-service
                port:
                  number: 80
            # ✅ USER middleware
            middlewares:
              - name: strip-user
                namespace: multiapp-prod
