apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminmvc
  labels:
    app: adminmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminmvc
  template:
    metadata:
      labels:
        app: adminmvc
    spec:
      containers:
        - name: adminmvc
          image: rakeshdev12/adminmvc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
