apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mvc-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Values.namespace }}-strip-prefix@kubernetescrd
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: adminmvc-service
                port:
                  number: 80
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: usermvc-service
                port:
                  number: 80
