apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermvc
  labels:
    app: usermvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermvc
  template:
    metadata:
      labels:
        app: usermvc
    spec:
      containers:
        - name: usermvc
          image: rakeshdev12/usermvc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
