name: CI/CD Auto Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push AdminMVC
      run: |
        docker build -t rakeshdev12/adminmvc:latest ./AdminMVC
        docker push rakeshdev12/adminmvc:latest

    - name: Build & Push UserMVC
      run: |
        docker build -t rakeshdev12/usermvc:latest ./UserMVC
        docker push rakeshdev12/usermvc:latest

    - name: Setup kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-prod --validate=false
        kubectl rollout restart deployment adminmvc -n multiapp-prod
        kubectl rollout restart deployment usermvc -n multiapp-prod
